// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: core.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addFamilyMember = `-- name: AddFamilyMember :exec
INSERT INTO family_members (family_id, user_id, role)
VALUES ($1, $2, $3)
ON CONFLICT (family_id, user_id)
DO UPDATE SET role = EXCLUDED.role
`

type AddFamilyMemberParams struct {
	FamilyID pgtype.UUID `json:"family_id"`
	UserID   pgtype.UUID `json:"user_id"`
	Role     string      `json:"role"`
}

func (q *Queries) AddFamilyMember(ctx context.Context, arg AddFamilyMemberParams) error {
	_, err := q.db.Exec(ctx, addFamilyMember, arg.FamilyID, arg.UserID, arg.Role)
	return err
}

const createFamily = `-- name: CreateFamily :one
INSERT INTO families (name, family_type)
VALUES ($1, $2)
RETURNING id, name, family_type, created_at, updated_at
`

type CreateFamilyParams struct {
	Name       string `json:"name"`
	FamilyType string `json:"family_type"`
}

func (q *Queries) CreateFamily(ctx context.Context, arg CreateFamilyParams) (Family, error) {
	row := q.db.QueryRow(ctx, createFamily, arg.Name, arg.FamilyType)
	var i Family
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.FamilyType,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (email, display_name, role, password_hash)
VALUES ($1, $2, $3, $4)
RETURNING id, email, display_name, role, password_hash, must_change_password, disabled_at, created_at, updated_at
`

type CreateUserParams struct {
	Email        string `json:"email"`
	DisplayName  string `json:"display_name"`
	Role         string `json:"role"`
	PasswordHash string `json:"password_hash"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.Email,
		arg.DisplayName,
		arg.Role,
		arg.PasswordHash,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.DisplayName,
		&i.Role,
		&i.PasswordHash,
		&i.MustChangePassword,
		&i.DisabledAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const disableUser = `-- name: DisableUser :exec
UPDATE users
SET disabled_at = now(), updated_at = now()
WHERE id = $1
`

func (q *Queries) DisableUser(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, disableUser, id)
	return err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, email, display_name, role, password_hash, must_change_password, disabled_at, created_at, updated_at FROM users
WHERE email = $1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.DisplayName,
		&i.Role,
		&i.PasswordHash,
		&i.MustChangePassword,
		&i.DisabledAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listHousingOptionsByFamily = `-- name: ListHousingOptionsByFamily :many
SELECT id, family_id, name, housing_type, location, unit_type, purchase_price_cents, grant_amount_cents, loan_type, loan_amount_cents, interest_rate_bps, loan_tenure_months, downpayment_percent_bps, renovation_budget_cents, furniture_budget_cents, legal_fees_cents, buyer_stamp_duty_cents, monthly_maintenance_cents, expected_key_collection_date, created_at, updated_at FROM housing_options
WHERE family_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListHousingOptionsByFamily(ctx context.Context, familyID pgtype.UUID) ([]HousingOption, error) {
	rows, err := q.db.Query(ctx, listHousingOptionsByFamily, familyID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []HousingOption{}
	for rows.Next() {
		var i HousingOption
		if err := rows.Scan(
			&i.ID,
			&i.FamilyID,
			&i.Name,
			&i.HousingType,
			&i.Location,
			&i.UnitType,
			&i.PurchasePriceCents,
			&i.GrantAmountCents,
			&i.LoanType,
			&i.LoanAmountCents,
			&i.InterestRateBps,
			&i.LoanTenureMonths,
			&i.DownpaymentPercentBps,
			&i.RenovationBudgetCents,
			&i.FurnitureBudgetCents,
			&i.LegalFeesCents,
			&i.BuyerStampDutyCents,
			&i.MonthlyMaintenanceCents,
			&i.ExpectedKeyCollectionDate,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPersonProfilesByFamily = `-- name: ListPersonProfilesByFamily :many
SELECT id, family_id, name, age, relationship_label, employment_status, gross_monthly_income_cents, expected_future_income_cents, expected_income_start_date, graduation_date, ord_date, cash_savings_cents, cpf_oa_cents, cpf_sa_cents, cpf_ma_cents, monthly_expenses_cents, created_at, updated_at FROM person_profiles
WHERE family_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListPersonProfilesByFamily(ctx context.Context, familyID pgtype.UUID) ([]PersonProfile, error) {
	rows, err := q.db.Query(ctx, listPersonProfilesByFamily, familyID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PersonProfile{}
	for rows.Next() {
		var i PersonProfile
		if err := rows.Scan(
			&i.ID,
			&i.FamilyID,
			&i.Name,
			&i.Age,
			&i.RelationshipLabel,
			&i.EmploymentStatus,
			&i.GrossMonthlyIncomeCents,
			&i.ExpectedFutureIncomeCents,
			&i.ExpectedIncomeStartDate,
			&i.GraduationDate,
			&i.OrdDate,
			&i.CashSavingsCents,
			&i.CpfOaCents,
			&i.CpfSaCents,
			&i.CpfMaCents,
			&i.MonthlyExpensesCents,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserFamilies = `-- name: ListUserFamilies :many
SELECT f.id, f.name, f.family_type, f.created_at, f.updated_at
FROM families f
JOIN family_members fm ON fm.family_id = f.id
WHERE fm.user_id = $1
ORDER BY f.created_at DESC
`

func (q *Queries) ListUserFamilies(ctx context.Context, userID pgtype.UUID) ([]Family, error) {
	rows, err := q.db.Query(ctx, listUserFamilies, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Family{}
	for rows.Next() {
		var i Family
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.FamilyType,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
