// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type AdminAccessKey struct {
	ID        pgtype.UUID        `json:"id"`
	UserID    pgtype.UUID        `json:"user_id"`
	TokenHash string             `json:"token_hash"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
	UsedAt    pgtype.Timestamptz `json:"used_at"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type CpfProfile struct {
	PersonProfileID      pgtype.UUID        `json:"person_profile_id"`
	OrdinaryAccountCents int64              `json:"ordinary_account_cents"`
	SpecialAccountCents  int64              `json:"special_account_cents"`
	MedisaveAccountCents int64              `json:"medisave_account_cents"`
	UpdatedAt            pgtype.Timestamptz `json:"updated_at"`
}

type Family struct {
	ID         pgtype.UUID        `json:"id"`
	Name       string             `json:"name"`
	FamilyType string             `json:"family_type"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
}

type FamilyInvite struct {
	ID        pgtype.UUID        `json:"id"`
	FamilyID  pgtype.UUID        `json:"family_id"`
	CodeHash  string             `json:"code_hash"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
	RevokedAt pgtype.Timestamptz `json:"revoked_at"`
	CreatedBy pgtype.UUID        `json:"created_by"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type FamilyMember struct {
	FamilyID pgtype.UUID        `json:"family_id"`
	UserID   pgtype.UUID        `json:"user_id"`
	Role     string             `json:"role"`
	JoinedAt pgtype.Timestamptz `json:"joined_at"`
}

type HousingOption struct {
	ID                        pgtype.UUID        `json:"id"`
	FamilyID                  pgtype.UUID        `json:"family_id"`
	Name                      string             `json:"name"`
	HousingType               string             `json:"housing_type"`
	Location                  string             `json:"location"`
	UnitType                  string             `json:"unit_type"`
	PurchasePriceCents        int64              `json:"purchase_price_cents"`
	GrantAmountCents          int64              `json:"grant_amount_cents"`
	LoanType                  string             `json:"loan_type"`
	LoanAmountCents           int64              `json:"loan_amount_cents"`
	InterestRateBps           int32              `json:"interest_rate_bps"`
	LoanTenureMonths          int32              `json:"loan_tenure_months"`
	DownpaymentPercentBps     int32              `json:"downpayment_percent_bps"`
	RenovationBudgetCents     int64              `json:"renovation_budget_cents"`
	FurnitureBudgetCents      int64              `json:"furniture_budget_cents"`
	LegalFeesCents            int64              `json:"legal_fees_cents"`
	BuyerStampDutyCents       int64              `json:"buyer_stamp_duty_cents"`
	MonthlyMaintenanceCents   int64              `json:"monthly_maintenance_cents"`
	ExpectedKeyCollectionDate pgtype.Date        `json:"expected_key_collection_date"`
	CreatedAt                 pgtype.Timestamptz `json:"created_at"`
	UpdatedAt                 pgtype.Timestamptz `json:"updated_at"`
}

type PersonIncomeHistory struct {
	ID                        pgtype.UUID        `json:"id"`
	PersonProfileID           pgtype.UUID        `json:"person_profile_id"`
	FamilyID                  pgtype.UUID        `json:"family_id"`
	PersonName                string             `json:"person_name"`
	GrossMonthlyIncomeCents   int64              `json:"gross_monthly_income_cents"`
	ExpectedFutureIncomeCents int64              `json:"expected_future_income_cents"`
	RecordedAt                pgtype.Timestamptz `json:"recorded_at"`
}

type PersonProfile struct {
	ID                        pgtype.UUID        `json:"id"`
	FamilyID                  pgtype.UUID        `json:"family_id"`
	Name                      string             `json:"name"`
	Age                       int32              `json:"age"`
	RelationshipLabel         string             `json:"relationship_label"`
	EmploymentStatus          string             `json:"employment_status"`
	GrossMonthlyIncomeCents   int64              `json:"gross_monthly_income_cents"`
	ExpectedFutureIncomeCents int64              `json:"expected_future_income_cents"`
	ExpectedIncomeStartDate   pgtype.Date        `json:"expected_income_start_date"`
	GraduationDate            pgtype.Date        `json:"graduation_date"`
	OrdDate                   pgtype.Date        `json:"ord_date"`
	CashSavingsCents          int64              `json:"cash_savings_cents"`
	CpfOaCents                int64              `json:"cpf_oa_cents"`
	CpfSaCents                int64              `json:"cpf_sa_cents"`
	CpfMaCents                int64              `json:"cpf_ma_cents"`
	MonthlyExpensesCents      int64              `json:"monthly_expenses_cents"`
	CreatedAt                 pgtype.Timestamptz `json:"created_at"`
	UpdatedAt                 pgtype.Timestamptz `json:"updated_at"`
	LinkedUserID              pgtype.UUID        `json:"linked_user_id"`
}

type Session struct {
	ID        pgtype.UUID        `json:"id"`
	UserID    pgtype.UUID        `json:"user_id"`
	TokenHash string             `json:"token_hash"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
	RevokedAt pgtype.Timestamptz `json:"revoked_at"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type User struct {
	ID                 pgtype.UUID        `json:"id"`
	Email              string             `json:"email"`
	DisplayName        string             `json:"display_name"`
	Role               string             `json:"role"`
	PasswordHash       string             `json:"password_hash"`
	MustChangePassword bool               `json:"must_change_password"`
	DisabledAt         pgtype.Timestamptz `json:"disabled_at"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	UpdatedAt          pgtype.Timestamptz `json:"updated_at"`
}
